version: '3'
services:
  nuxt:
    build: ./nuxt
    command: npm run dev 
    privileged: true
    ports:
      - '3000:3000'
    volumes:
      - ./nuxt/src:/home/app/nuxt
      - /home/app/nuxt/node_modules